### ISSUE TITLE
Birt Report not found

### ISSUE THREAD

**Issue by arno974** [lavadiablo/docker-birt-host#1]
Hi,

First of all, thanks for this birt docker images.
The birt report example [1] works fine, but when I try to get my own rptdesign [2], I get this error:
- The report file : test_web.rptdesign does not exist or contains errors.
  This test_web file is a very basic report that only contains a text area with "hello word".

My own reports are in folder located in /home/admin/birt_report. And the docker run is : 
`docker run --name birt_host -p 9002:8080 -v /home/admin/birt_report:/var/lib/tomcat7/webapps/birt/reports:ro -d lavadiablo/docker-birt-host`

Please could you tell me what I'm doing wrong.

Thanks

Arnaud

[1] http://mywebserver:9002/birt/frameset?__report=test.rptdesign&sample=my+parameter
[2] http://mywebserver:9002/birt/frameset?__report=test_web.rptdesign

**Comment by lavadiablo** [comment]
As all your reports are stored in the folder "reports", you need add it in the url.
In your case,
http://mywebserver:9002/birt/frameset?__report=reports/test_web.rptdesign

**Comment by arno974** [comment]
Oh yeah ! Thanks lavadiablo :)
